#!/usr/bin/env bash

function cpulook/initialize-cpudir {
  unset -f "$FUNCNAME"

  local script=$0
  if [[ -h $script ]]; then
    local path=$(realpath "$0" || readlink -f "$0" || /bin/readlink -f "$script") 2>/dev/null
    [[ $path ]] && script=$path
  fi

  [[ $script =~ ^(/?)(.*/)[^/]*$ ]]
  local script_dir=${BASH_REMATCH[1]:-$PWD/}${BASH_REMATCH[2]}
  script_dir=${script_dir%/}
  if [[ -d ${script_dir:-/} ]]; then
    cpudir=$script_dir
  elif local dir=${XDG_DATA_HOME:-$HOME/.local/share}/cpulook; [[ -d $dir ]]; then
    cpudir=$dir
  else
    cpudir=$script_dir
  fi

  # Go to the parent directory until we find $cpudir/lib/cpudef.bash
  while
    local common=$cpudir/lib/cpudef.bash
    if [[ -f $common ]]; then
      if [[ ! -r $common ]]; then
        printf '%s\n' "$script: permission denied for the cpulook directory." >&2
        return 1
      fi
      source "$common"
      return "$?"
    fi
    [[ $cpudir == */* ]]
  do
    cpudir=${cpudir%/*}
  done

  cpudir=
  printf '%s\n' "$script: failed to detect the cpulook directory." >&2
  return 1
}
cpulook/initialize-cpudir || exit "$?"
##----CPULOOK_COMMON_HEADER_END----

source "$cpudir/lib/echox.bash"
source "$cpudir/m/switch"

flog=$cpudir/cpuseekd.log
datetime=$(date +'[%x %T]')
function log_submit {
  cpulook/print "$datetime $1" >> "$flog"
  echom "$datetime $1"
}

cpulook/system:"$cpulook_system"/kill "$@"
