#!/bin/bash

function cpudir.initialize {
  cpudir=${MWGDIR:-$HOME/.mwg}/share/cpulook
  [[ -d $cpudir ]] && return
  local _scr=$(readlink -f "$0" || /bin/readlink -f "$0" || echo "$0")
  local _dir=${_scr%/*}
  [[ $_dir = "$_scr" ]] && _dir=.
  [[ ! $_dir ]] && _dir=/
  cpudir=$_dir
}
cpudir.initialize

source "$cpudir/cpudefs.sh"

host=$($cpudir/cpugethost.sh "$1") || exit 1

rsh.dispatch "$host" last|less
