#!/usr/bin/env bash

function cpulook/initialize-cpudir {
  unset -f "$FUNCNAME"

  local script=$0
  if [[ -h $script ]]; then
    local path=$(realpath "$0" || readlink -f "$0" || /bin/readlink -f "$script") 2>/dev/null
    [[ $path ]] && script=$path
  fi

  local script_dir=${script%/*}
  [[ $script_dir == "$script" ]] && script_dir=.
  if [[ -d ${script_dir:=/} ]]; then
    cpudir=$script_dir
  elif local dir=${XDG_DATA_HOME:-$HOME/.local/share}/cpulook; [[ -d $dir ]]; then
    cpudir=$dir
  else
    cpudir=$script_dir
  fi

  # Note: The file ending with .sh is supposed to be a helper script, which is
  # already located in the lib subdirectory.
  [[ $script == *.sh ]] && cpudir=$cpudir/..

  local common=$cpudir/lib/common.bash
  if [[ ! -f $common ]]; then
    printf '%s\n' "$script: failed to detect the cpulook directory." >&2
    exit 2
  elif [[ ! -r $common ]]; then
    printf '%s\n' "$script: permission denied for the cpulook directory." >&2
    exit 2
  else
    source "$common"
  fi
}
cpulook/initialize-cpudir
##----CPULOOK_COMMON_HEADER_END----

host=$("$cpudir"/lib/cpugethost.sh "$1") || exit 1

rsh.dispatch "$host" last | cpulook/view
