#!/bin/bash
# to source

: ${local_cpudir:=$HOME/.mwg/share/cpulook}

case "$1" in
(rsh)
  shift
  (cd "$local_cpudir"; eval "$*")
  return 0 ;;
(*)
  echo not supported operation >&2
  return 1 ;;
esac
